Allow staging images only on OOM staging branch
Issue-ID: INT-1055
Signed-off-by: Gary Wu <gary.wu@futurewei.com>
Change-Id: Idde622a1b4160f6f87b42e0252d902b5f3dd84d4

diff --git a/jjb/oom/oom-helm.yaml b/jjb/oom/oom-helm.yaml
--- a/jjb/oom/oom-helm.yaml
+++ b/jjb/oom/oom-helm.yaml
@@ -12,17 +12,21 @@
         #!/bin/bash
         set -e -o pipefail
         cd kubernetes/
-        if grep -r -n -E ':\s*onap/.*:.*(STAGING|SNAPSHOT|latest).*'; then
-          echo "[ERROR] Only release images are allowed in helm charts."
-          exit 1
+        if [ "$GERRIT_BRANCH" != "staging" ]; then
+          if grep -r -n -E ':\s*onap/.*:.*(STAGING|SNAPSHOT|latest).*'; then
+            echo "[ERROR] Only release images are allowed in helm charts."
+            exit 1
+          fi
         fi
         make all
     subproject_build_script: |
         #!/bin/bash
         cd kubernetes/
-        if grep -r -n -E ':\s*onap/.*:.*(STAGING|SNAPSHOT|latest).*'; then
-          echo "[ERROR] Only release images are allowed in helm charts."
-          exit 1
+        if [ "$GERRIT_BRANCH" != "staging" ]; then
+          if grep -r -n -E ':\s*onap/.*:.*(STAGING|SNAPSHOT|latest).*'; then
+            echo "[ERROR] Only release images are allowed in helm charts."
+            exit 1
+          fi
         fi
         make common
         make {subproject}
