Only allow release images in helm charts
Going forward, only released docker images are
allowed in helm charts.  Teams wishing to test
staging versions need to do so via a helm
override file.

Issue-ID: INT-1055
Signed-off-by: Gary Wu <gwu@futurewei.com>
Change-Id: Ieba662f8ec3474cca1e0d55dd7e3692ffdb726f5

diff --git a/jjb/oom/oom-helm.yaml b/jjb/oom/oom-helm.yaml
--- a/jjb/oom/oom-helm.yaml
+++ b/jjb/oom/oom-helm.yaml
@@ -12,10 +12,18 @@
         #!/bin/bash
         set -e -o pipefail
         cd kubernetes/
+        if grep -r -n -E ':\s*onap/.*:.*(STAGING|SNAPSHOT|latest).*'; then
+          echo "[ERROR] Only release images are allowed in helm charts."
+          exit 1
+        fi
         make all
     subproject_build_script: |
         #!/bin/bash
         cd kubernetes/
+        if grep -r -n -E ':\s*onap/.*:.*(STAGING|SNAPSHOT|latest).*'; then
+          echo "[ERROR] Only release images are allowed in helm charts."
+          exit 1
+        fi
         make common
         make {subproject}
     oom_post_build_script: !include-raw-escape: shell/publish_helm_charts.sh
